import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import baseUrl from "@/services/baseUrl";

import { Hind_Siliguri } from "next/font/google";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "বাজার দর — প্রয়োজনীয় পণ্যের দাম এক নজরে",
  description:
    "চাল, ডাল, তেল, সবজি, মাছ, মাংস, ডিম ও মসলার দাম — বাজারভিত্তিক বিস্তারিত, গড়, সর্বনিম্ন-সর্বোচ্চ এবং দামের পরিবর্তন এক জায়গায়।",
};

const getCategories = async () => {
  const res = await fetch(`${baseUrl}/categories`);
  const data = res.json();
  return data;
};

export default async function RootLayout({ children }) {
  const categories = await getCategories();
  // console.log(categories);
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.className} antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Navbar categories={categories} />
        {children}
      </body>
    </html>
  );
}
